# Generated by Django 3.0.8 on 2020-08-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200724_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=122)),
                ('phone1', models.CharField(max_length=12)),
                ('email1', models.CharField(max_length=122)),
                ('desc1', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
