# Generated by Django 3.0.8 on 2020-08-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200801_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date1',
            new_name='date',
        ),
    ]
