# Generated by Django 3.0.8 on 2020-09-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200901_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.AddField(
            model_name='product',
            name='Author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
