# Generated by Django 3.0.8 on 2020-09-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200909_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
