# Generated by Django 3.0.8 on 2020-09-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_desc2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainprice',
            field=models.IntegerField(default=0),
        ),
    ]
