# Generated by Django 3.0.8 on 2020-09-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200910_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='name2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phone2',
        ),
    ]
