# Generated by Django 3.0.8 on 2020-09-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200910_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date2',
        ),
    ]
