# Generated by Django 3.0.8 on 2020-09-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200910_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date2',
        ),
    ]
