# Generated by Django 3.0.8 on 2020-09-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
