# Generated by Django 3.0.8 on 2020-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
